import type { NextPage, InferGetStaticPropsType, GetStaticPaths, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { fetchAllCrews, fetchCrew } from '../../lib/client'

type PageProps = InferGetStaticPropsType<typeof getStaticProps>

const Crew: NextPage<PageProps> = ({ crew }) => {
  return (
    <div>
      <Head>
        <title>Space X Crew | {crew.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>{crew.name}</h1>
      <div>
        <Image src={crew.image} alt={crew.name} height='400' width='300' objectFit={'contain'} />
      </div>
      <div>
        <h3>{crew.agency}</h3>
        <p>
          <a href={crew.wikipedia}>Wikipedia</a>
        </p>
      </div>
    </div>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const crews = await fetchAllCrews()
  const paths = crews.map((crew) => ({
    params: { id: crew.id },
  }))

  return { paths, fallback: false }
}

export const getStaticProps = async (context: GetStaticPropsContext) => {
  const crewId = context.params?.id as string
  const crew = await fetchCrew(crewId)

  // Pass post data to the page via props
  return { props: { crew } }
}

export default Crew
