import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { fetchAllCrews } from '../lib/client'
import { Title } from '../components/style'

type PageProps = InferGetStaticPropsType<typeof getStaticProps>

const Crews: NextPage<PageProps> = ({ crews }) => {
  return (
    <div>
      <Head>
        <title>Space X Crew</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Title>Space X Crew</Title>
      <ul>
        {crews.map((crew) => {
          return (
            <li key={crew.id}>
              <Image
                src={crew.image}
                alt={crew.name}
                height='320'
                width='320'
                objectFit={'contain'}
              />
              <Link href={`/crews/${crew.id}`}>
                <a>{crew.name}</a>
              </Link>
            </li>
          )
        })}
      </ul>
    </div>
  )
}

export const getStaticProps = async () => {
  const crews = await fetchAllCrews()

  // Pass post data to the page via props
  return { props: { crews } }
}

export default Crews
